name: Build docker images
on: [push]

jobs:
  build:
    name: Build mothd
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve code
        uses: actions/checkout@v1
      - name: Build mothd
        run: docker build -f Dockerfile.moth .
  build-devel:
    name: Build moth-devel
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve code
        uses: actions/checkout@v1
      - name: Build mothd
        run: docker build -f Dockerfile.moth-devel .

